import re
from functools import reduce

from src.parser.diagram.dict.grammar import get_production_rules
from src.parser.utils import SymbolType

TRANSITION_DIAGRAM = [
    {
        "name": "Program",
        "predict_set": {"$", "int", "void"},
        "follow_set": ["$"],
        "states": [
            {"id": 1, "start": True, "end": False},
            {"id": 2, "start": False, "end": True},
            {"id": 3, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 1,
                "state_dst_id": 3,
                "type": 1,
                "name": "Declaration_list",
                "predict": {
                    "$",
                    ";",
                    "if",
                    "void",
                    "(",
                    "int",
                    "repeat",
                    "break",
                    "return",
                    "}",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 3,
                "state_dst_id": 2,
                "type": 0,
                "name": "$",
                "predict": ["$"],
            },
        ],
    },
    {
        "name": "Declaration_list",
        "predict_set": {
            "$",
            ";",
            "if",
            "void",
            "(",
            "int",
            "repeat",
            "break",
            "return",
            "}",
            "ID",
            "{",
            "NUM",
        },
        "follow_set": [
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
        ],
        "states": [
            {"id": 4, "start": True, "end": False},
            {"id": 5, "start": False, "end": True},
            {"id": 6, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 4,
                "state_dst_id": 6,
                "type": 1,
                "name": "Declaration",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 6,
                "state_dst_id": 5,
                "type": 1,
                "name": "Declaration_list",
                "predict": {
                    "$",
                    ";",
                    "if",
                    "void",
                    "(",
                    "int",
                    "repeat",
                    "break",
                    "return",
                    "}",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 4,
                "state_dst_id": 5,
                "type": 2,
                "name": "ε",
                "predict": [
                    "$",
                    "{",
                    "break",
                    ";",
                    "if",
                    "repeat",
                    "return",
                    "ID",
                    "(",
                    "NUM",
                    "}",
                ],
            },
        ],
    },
    {
        "name": "Declaration",
        "predict_set": {"int", "void"},
        "follow_set": [
            "int",
            "void",
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
        ],
        "states": [
            {"id": 7, "start": True, "end": False},
            {"id": 8, "start": False, "end": True},
            {"id": 9, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 7,
                "state_dst_id": 9,
                "type": 1,
                "name": "Declaration_initial",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 9,
                "state_dst_id": 8,
                "type": 1,
                "name": "Declaration_prime",
                "predict": {";", "[", "("},
            },
        ],
    },
    {
        "name": "Declaration_initial",
        "predict_set": {"int", "void"},
        "follow_set": ["(", ";", "[", ",", ")"],
        "states": [
            {"id": 10, "start": True, "end": False},
            {"id": 11, "start": False, "end": True},
            {"id": 12, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 10,
                "state_dst_id": 12,
                "type": 1,
                "name": "Type_specifier",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 12,
                "state_dst_id": 11,
                "type": 0,
                "name": "ID",
                "predict": ["ID"],
            },
        ],
    },
    {
        "name": "Declaration_prime",
        "predict_set": {";", "[", "("},
        "follow_set": [
            "int",
            "void",
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
        ],
        "states": [
            {"id": 13, "start": True, "end": False},
            {"id": 14, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 13,
                "state_dst_id": 14,
                "type": 1,
                "name": "Fun_declaration_prime",
                "predict": {"("},
            },
            {
                "state_src_id": 13,
                "state_dst_id": 14,
                "type": 1,
                "name": "Var_declaration_prime",
                "predict": {";", "["},
            },
        ],
    },
    {
        "name": "Var_declaration_prime",
        "predict_set": {";", "["},
        "follow_set": [
            "int",
            "void",
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
        ],
        "states": [
            {"id": 15, "start": True, "end": False},
            {"id": 16, "start": False, "end": True},
            {"id": 17, "start": False, "end": False},
            {"id": 18, "start": False, "end": False},
            {"id": 19, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 15,
                "state_dst_id": 16,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
            {
                "state_src_id": 15,
                "state_dst_id": 17,
                "type": 0,
                "name": "[",
                "predict": ["["],
            },
            {
                "state_src_id": 17,
                "state_dst_id": 18,
                "type": 0,
                "name": "NUM",
                "predict": ["NUM"],
            },
            {
                "state_src_id": 18,
                "state_dst_id": 19,
                "type": 0,
                "name": "]",
                "predict": ["]"],
            },
            {
                "state_src_id": 19,
                "state_dst_id": 16,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
        ],
    },
    {
        "name": "Fun_declaration_prime",
        "predict_set": {"("},
        "follow_set": [
            "int",
            "void",
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
        ],
        "states": [
            {"id": 20, "start": True, "end": False},
            {"id": 21, "start": False, "end": True},
            {"id": 22, "start": False, "end": False},
            {"id": 23, "start": False, "end": False},
            {"id": 24, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 20,
                "state_dst_id": 22,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 22,
                "state_dst_id": 23,
                "type": 1,
                "name": "Params",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 23,
                "state_dst_id": 24,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 24,
                "state_dst_id": 21,
                "type": 1,
                "name": "Compound_stmt",
                "predict": {"{"},
            },
        ],
    },
    {
        "name": "Type_specifier",
        "predict_set": {"int", "void"},
        "follow_set": ["ID"],
        "states": [
            {"id": 25, "start": True, "end": False},
            {"id": 26, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 25,
                "state_dst_id": 26,
                "type": 0,
                "name": "int",
                "predict": ["int"],
            },
            {
                "state_src_id": 25,
                "state_dst_id": 26,
                "type": 0,
                "name": "void",
                "predict": ["void"],
            },
        ],
    },
    {
        "name": "Params",
        "predict_set": {"int", "void"},
        "follow_set": [")"],
        "states": [
            {"id": 27, "start": True, "end": False},
            {"id": 28, "start": False, "end": True},
            {"id": 29, "start": False, "end": False},
            {"id": 30, "start": False, "end": False},
            {"id": 31, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 27,
                "state_dst_id": 29,
                "type": 0,
                "name": "int",
                "predict": ["int"],
            },
            {
                "state_src_id": 29,
                "state_dst_id": 30,
                "type": 0,
                "name": "ID",
                "predict": ["ID"],
            },
            {
                "state_src_id": 30,
                "state_dst_id": 31,
                "type": 1,
                "name": "Param_prime",
                "predict": {"[", ")", ","},
            },
            {
                "state_src_id": 31,
                "state_dst_id": 28,
                "type": 1,
                "name": "Param_list",
                "predict": {")", ","},
            },
            {
                "state_src_id": 27,
                "state_dst_id": 28,
                "type": 0,
                "name": "void",
                "predict": ["void"],
            },
        ],
    },
    {
        "name": "Param_list",
        "predict_set": {")", ","},
        "follow_set": [")"],
        "states": [
            {"id": 32, "start": True, "end": False},
            {"id": 33, "start": False, "end": True},
            {"id": 34, "start": False, "end": False},
            {"id": 35, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 32,
                "state_dst_id": 34,
                "type": 0,
                "name": ",",
                "predict": [","],
            },
            {
                "state_src_id": 34,
                "state_dst_id": 35,
                "type": 1,
                "name": "Param",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 35,
                "state_dst_id": 33,
                "type": 1,
                "name": "Param_list",
                "predict": {")", ","},
            },
            {
                "state_src_id": 32,
                "state_dst_id": 33,
                "type": 2,
                "name": "ε",
                "predict": [")"],
            },
        ],
    },
    {
        "name": "Param",
        "predict_set": {"int", "void"},
        "follow_set": [",", ")"],
        "states": [
            {"id": 36, "start": True, "end": False},
            {"id": 37, "start": False, "end": True},
            {"id": 38, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 36,
                "state_dst_id": 38,
                "type": 1,
                "name": "Declaration_initial",
                "predict": {"int", "void"},
            },
            {
                "state_src_id": 38,
                "state_dst_id": 37,
                "type": 1,
                "name": "Param_prime",
                "predict": {"[", ")", ","},
            },
        ],
    },
    {
        "name": "Param_prime",
        "predict_set": {"[", ")", ","},
        "follow_set": [",", ")"],
        "states": [
            {"id": 39, "start": True, "end": False},
            {"id": 40, "start": False, "end": True},
            {"id": 41, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 39,
                "state_dst_id": 41,
                "type": 0,
                "name": "[",
                "predict": ["["],
            },
            {
                "state_src_id": 41,
                "state_dst_id": 40,
                "type": 0,
                "name": "]",
                "predict": ["]"],
            },
            {
                "state_src_id": 39,
                "state_dst_id": 40,
                "type": 2,
                "name": "ε",
                "predict": [",", ")"],
            },
        ],
    },
    {
        "name": "Compound_stmt",
        "predict_set": {"{"},
        "follow_set": [
            "int",
            "void",
            "$",
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 42, "start": True, "end": False},
            {"id": 43, "start": False, "end": True},
            {"id": 44, "start": False, "end": False},
            {"id": 45, "start": False, "end": False},
            {"id": 46, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 42,
                "state_dst_id": 44,
                "type": 0,
                "name": "{",
                "predict": ["{"],
            },
            {
                "state_src_id": 44,
                "state_dst_id": 45,
                "type": 1,
                "name": "Declaration_list",
                "predict": {
                    "$",
                    ";",
                    "if",
                    "void",
                    "(",
                    "int",
                    "repeat",
                    "break",
                    "return",
                    "}",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 45,
                "state_dst_id": 46,
                "type": 1,
                "name": "Statement_list",
                "predict": {
                    ";",
                    "if",
                    "ID",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "}",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 46,
                "state_dst_id": 43,
                "type": 0,
                "name": "}",
                "predict": ["}"],
            },
        ],
    },
    {
        "name": "Statement_list",
        "predict_set": {
            ";",
            "if",
            "ID",
            "(",
            "repeat",
            "break",
            "return",
            "}",
            "{",
            "NUM",
        },
        "follow_set": ["}"],
        "states": [
            {"id": 47, "start": True, "end": False},
            {"id": 48, "start": False, "end": True},
            {"id": 49, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 47,
                "state_dst_id": 49,
                "type": 1,
                "name": "Statement",
                "predict": {
                    ";",
                    "if",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 49,
                "state_dst_id": 48,
                "type": 1,
                "name": "Statement_list",
                "predict": {
                    ";",
                    "if",
                    "ID",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "}",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 47,
                "state_dst_id": 48,
                "type": 2,
                "name": "ε",
                "predict": ["}"],
            },
        ],
    },
    {
        "name": "Statement",
        "predict_set": {";", "if", "(", "repeat", "break", "return", "ID", "{", "NUM"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 50, "start": True, "end": False},
            {"id": 51, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 50,
                "state_dst_id": 51,
                "type": 1,
                "name": "Expression_stmt",
                "predict": {";", "break", "(", "ID", "NUM"},
            },
            {
                "state_src_id": 50,
                "state_dst_id": 51,
                "type": 1,
                "name": "Compound_stmt",
                "predict": {"{"},
            },
            {
                "state_src_id": 50,
                "state_dst_id": 51,
                "type": 1,
                "name": "Selection_stmt",
                "predict": {"if"},
            },
            {
                "state_src_id": 50,
                "state_dst_id": 51,
                "type": 1,
                "name": "Iteration_stmt",
                "predict": {"repeat"},
            },
            {
                "state_src_id": 50,
                "state_dst_id": 51,
                "type": 1,
                "name": "Return_stmt",
                "predict": {"return"},
            },
        ],
    },
    {
        "name": "Expression_stmt",
        "predict_set": {";", "break", "(", "ID", "NUM"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 52, "start": True, "end": False},
            {"id": 53, "start": False, "end": True},
            {"id": 54, "start": False, "end": False},
            {"id": 55, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 52,
                "state_dst_id": 54,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 54,
                "state_dst_id": 53,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
            {
                "state_src_id": 52,
                "state_dst_id": 55,
                "type": 0,
                "name": "break",
                "predict": ["break"],
            },
            {
                "state_src_id": 55,
                "state_dst_id": 53,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
            {
                "state_src_id": 52,
                "state_dst_id": 53,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
        ],
    },
    {
        "name": "Selection_stmt",
        "predict_set": {"if"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 56, "start": True, "end": False},
            {"id": 57, "start": False, "end": True},
            {"id": 58, "start": False, "end": False},
            {"id": 59, "start": False, "end": False},
            {"id": 60, "start": False, "end": False},
            {"id": 61, "start": False, "end": False},
            {"id": 62, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 56,
                "state_dst_id": 58,
                "type": 0,
                "name": "if",
                "predict": ["if"],
            },
            {
                "state_src_id": 58,
                "state_dst_id": 59,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 59,
                "state_dst_id": 60,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 60,
                "state_dst_id": 61,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 61,
                "state_dst_id": 62,
                "type": 1,
                "name": "Statement",
                "predict": {
                    ";",
                    "if",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 62,
                "state_dst_id": 57,
                "type": 1,
                "name": "Else_stmt",
                "predict": {"endif", "else"},
            },
        ],
    },
    {
        "name": "Else_stmt",
        "predict_set": {"endif", "else"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 63, "start": True, "end": False},
            {"id": 64, "start": False, "end": True},
            {"id": 65, "start": False, "end": False},
            {"id": 66, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 63,
                "state_dst_id": 64,
                "type": 0,
                "name": "endif",
                "predict": ["endif"],
            },
            {
                "state_src_id": 63,
                "state_dst_id": 65,
                "type": 0,
                "name": "else",
                "predict": ["else"],
            },
            {
                "state_src_id": 65,
                "state_dst_id": 66,
                "type": 1,
                "name": "Statement",
                "predict": {
                    ";",
                    "if",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 66,
                "state_dst_id": 64,
                "type": 0,
                "name": "endif",
                "predict": ["endif"],
            },
        ],
    },
    {
        "name": "Iteration_stmt",
        "predict_set": {"repeat"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 67, "start": True, "end": False},
            {"id": 68, "start": False, "end": True},
            {"id": 69, "start": False, "end": False},
            {"id": 70, "start": False, "end": False},
            {"id": 71, "start": False, "end": False},
            {"id": 72, "start": False, "end": False},
            {"id": 73, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 67,
                "state_dst_id": 69,
                "type": 0,
                "name": "repeat",
                "predict": ["repeat"],
            },
            {
                "state_src_id": 69,
                "state_dst_id": 70,
                "type": 1,
                "name": "Statement",
                "predict": {
                    ";",
                    "if",
                    "(",
                    "repeat",
                    "break",
                    "return",
                    "ID",
                    "{",
                    "NUM",
                },
            },
            {
                "state_src_id": 70,
                "state_dst_id": 71,
                "type": 0,
                "name": "until",
                "predict": ["until"],
            },
            {
                "state_src_id": 71,
                "state_dst_id": 72,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 72,
                "state_dst_id": 73,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 73,
                "state_dst_id": 68,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
        ],
    },
    {
        "name": "Return_stmt",
        "predict_set": {"return"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 74, "start": True, "end": False},
            {"id": 75, "start": False, "end": True},
            {"id": 76, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 74,
                "state_dst_id": 76,
                "type": 0,
                "name": "return",
                "predict": ["return"],
            },
            {
                "state_src_id": 76,
                "state_dst_id": 75,
                "type": 1,
                "name": "Return_stmt_prime",
                "predict": {"(", "ID", ";", "NUM"},
            },
        ],
    },
    {
        "name": "Return_stmt_prime",
        "predict_set": {"(", "ID", ";", "NUM"},
        "follow_set": [
            "{",
            "break",
            ";",
            "if",
            "repeat",
            "return",
            "ID",
            "(",
            "NUM",
            "}",
            "endif",
            "else",
            "until",
        ],
        "states": [
            {"id": 77, "start": True, "end": False},
            {"id": 78, "start": False, "end": True},
            {"id": 79, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 77,
                "state_dst_id": 78,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
            {
                "state_src_id": 77,
                "state_dst_id": 79,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 79,
                "state_dst_id": 78,
                "type": 0,
                "name": ";",
                "predict": [";"],
            },
        ],
    },
    {
        "name": "Expression",
        "predict_set": {"ID", "NUM", "("},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 80, "start": True, "end": False},
            {"id": 81, "start": False, "end": True},
            {"id": 82, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 80,
                "state_dst_id": 81,
                "type": 1,
                "name": "Simple_expression_zegond",
                "predict": {"NUM", "("},
            },
            {
                "state_src_id": 80,
                "state_dst_id": 82,
                "type": 0,
                "name": "ID",
                "predict": ["ID"],
            },
            {
                "state_src_id": 82,
                "state_dst_id": 81,
                "type": 1,
                "name": "B",
                "predict": {
                    ";",
                    "+",
                    ")",
                    "(",
                    "=",
                    "]",
                    "[",
                    ",",
                    "==",
                    "*",
                    "-",
                    "<",
                },
            },
        ],
    },
    {
        "name": "B",
        "predict_set": {";", "+", ")", "(", "=", "]", "[", ",", "==", "*", "-", "<"},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 83, "start": True, "end": False},
            {"id": 84, "start": False, "end": True},
            {"id": 85, "start": False, "end": False},
            {"id": 86, "start": False, "end": False},
            {"id": 87, "start": False, "end": False},
            {"id": 88, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 83,
                "state_dst_id": 85,
                "type": 0,
                "name": "=",
                "predict": ["="],
            },
            {
                "state_src_id": 85,
                "state_dst_id": 84,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 83,
                "state_dst_id": 86,
                "type": 0,
                "name": "[",
                "predict": ["["],
            },
            {
                "state_src_id": 86,
                "state_dst_id": 87,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 87,
                "state_dst_id": 88,
                "type": 0,
                "name": "]",
                "predict": ["]"],
            },
            {
                "state_src_id": 88,
                "state_dst_id": 84,
                "type": 1,
                "name": "H",
                "predict": {";", "+", ")", "]", "=", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 83,
                "state_dst_id": 84,
                "type": 1,
                "name": "Simple_expression_prime",
                "predict": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
            },
        ],
    },
    {
        "name": "H",
        "predict_set": {";", "+", ")", "]", "=", ",", "==", "*", "-", "<"},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 89, "start": True, "end": False},
            {"id": 90, "start": False, "end": True},
            {"id": 91, "start": False, "end": False},
            {"id": 92, "start": False, "end": False},
            {"id": 93, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 89,
                "state_dst_id": 91,
                "type": 0,
                "name": "=",
                "predict": ["="],
            },
            {
                "state_src_id": 91,
                "state_dst_id": 90,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 89,
                "state_dst_id": 92,
                "type": 1,
                "name": "G",
                "predict": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 92,
                "state_dst_id": 93,
                "type": 1,
                "name": "D",
                "predict": {";", "+", ")", "]", ",", "==", "-", "<"},
            },
            {
                "state_src_id": 93,
                "state_dst_id": 90,
                "type": 1,
                "name": "C",
                "predict": {";", ")", "==", "<", "]", ","},
            },
        ],
    },
    {
        "name": "Simple_expression_zegond",
        "predict_set": {"NUM", "("},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 94, "start": True, "end": False},
            {"id": 95, "start": False, "end": True},
            {"id": 96, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 94,
                "state_dst_id": 96,
                "type": 1,
                "name": "Additive_expression_zegond",
                "predict": {"NUM", "("},
            },
            {
                "state_src_id": 96,
                "state_dst_id": 95,
                "type": 1,
                "name": "C",
                "predict": {";", ")", "==", "<", "]", ","},
            },
        ],
    },
    {
        "name": "Simple_expression_prime",
        "predict_set": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 97, "start": True, "end": False},
            {"id": 98, "start": False, "end": True},
            {"id": 99, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 97,
                "state_dst_id": 99,
                "type": 1,
                "name": "Additive_expression_prime",
                "predict": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 99,
                "state_dst_id": 98,
                "type": 1,
                "name": "C",
                "predict": {";", ")", "==", "<", "]", ","},
            },
        ],
    },
    {
        "name": "C",
        "predict_set": {";", ")", "==", "<", "]", ","},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 100, "start": True, "end": False},
            {"id": 101, "start": False, "end": True},
            {"id": 102, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 100,
                "state_dst_id": 102,
                "type": 1,
                "name": "Relop",
                "predict": {"<", "=="},
            },
            {
                "state_src_id": 102,
                "state_dst_id": 101,
                "type": 1,
                "name": "Additive_expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 100,
                "state_dst_id": 101,
                "type": 2,
                "name": "ε",
                "predict": [";", ")", "]", ","],
            },
        ],
    },
    {
        "name": "Relop",
        "predict_set": {"<", "=="},
        "follow_set": ["(", "ID", "NUM"],
        "states": [
            {"id": 103, "start": True, "end": False},
            {"id": 104, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 103,
                "state_dst_id": 104,
                "type": 0,
                "name": "<",
                "predict": ["<"],
            },
            {
                "state_src_id": 103,
                "state_dst_id": 104,
                "type": 0,
                "name": "==",
                "predict": ["=="],
            },
        ],
    },
    {
        "name": "Additive_expression",
        "predict_set": {"ID", "NUM", "("},
        "follow_set": [";", ")", "]", ","],
        "states": [
            {"id": 105, "start": True, "end": False},
            {"id": 106, "start": False, "end": True},
            {"id": 107, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 105,
                "state_dst_id": 107,
                "type": 1,
                "name": "Term",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 107,
                "state_dst_id": 106,
                "type": 1,
                "name": "D",
                "predict": {";", "+", ")", "]", ",", "==", "-", "<"},
            },
        ],
    },
    {
        "name": "Additive_expression_prime",
        "predict_set": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
        "follow_set": ["<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 108, "start": True, "end": False},
            {"id": 109, "start": False, "end": True},
            {"id": 110, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 108,
                "state_dst_id": 110,
                "type": 1,
                "name": "Term_prime",
                "predict": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 110,
                "state_dst_id": 109,
                "type": 1,
                "name": "D",
                "predict": {";", "+", ")", "]", ",", "==", "-", "<"},
            },
        ],
    },
    {
        "name": "Additive_expression_zegond",
        "predict_set": {"NUM", "("},
        "follow_set": ["<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 111, "start": True, "end": False},
            {"id": 112, "start": False, "end": True},
            {"id": 113, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 111,
                "state_dst_id": 113,
                "type": 1,
                "name": "Term_zegond",
                "predict": {"NUM", "("},
            },
            {
                "state_src_id": 113,
                "state_dst_id": 112,
                "type": 1,
                "name": "D",
                "predict": {";", "+", ")", "]", ",", "==", "-", "<"},
            },
        ],
    },
    {
        "name": "D",
        "predict_set": {";", "+", ")", "]", ",", "==", "-", "<"},
        "follow_set": ["<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 114, "start": True, "end": False},
            {"id": 115, "start": False, "end": True},
            {"id": 116, "start": False, "end": False},
            {"id": 117, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 114,
                "state_dst_id": 116,
                "type": 1,
                "name": "Addop",
                "predict": {"-", "+"},
            },
            {
                "state_src_id": 116,
                "state_dst_id": 117,
                "type": 1,
                "name": "Term",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 117,
                "state_dst_id": 115,
                "type": 1,
                "name": "D",
                "predict": {";", "+", ")", "]", ",", "==", "-", "<"},
            },
            {
                "state_src_id": 114,
                "state_dst_id": 115,
                "type": 2,
                "name": "ε",
                "predict": ["<", "==", ";", ")", "]", ","],
            },
        ],
    },
    {
        "name": "Addop",
        "predict_set": {"-", "+"},
        "follow_set": ["(", "ID", "NUM"],
        "states": [
            {"id": 118, "start": True, "end": False},
            {"id": 119, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 118,
                "state_dst_id": 119,
                "type": 0,
                "name": "+",
                "predict": ["+"],
            },
            {
                "state_src_id": 118,
                "state_dst_id": 119,
                "type": 0,
                "name": "-",
                "predict": ["-"],
            },
        ],
    },
    {
        "name": "Term",
        "predict_set": {"ID", "NUM", "("},
        "follow_set": ["+", "-", ";", ")", "<", "==", "]", ","],
        "states": [
            {"id": 120, "start": True, "end": False},
            {"id": 121, "start": False, "end": True},
            {"id": 122, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 120,
                "state_dst_id": 122,
                "type": 1,
                "name": "Factor",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 122,
                "state_dst_id": 121,
                "type": 1,
                "name": "G",
                "predict": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
            },
        ],
    },
    {
        "name": "Term_prime",
        "predict_set": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
        "follow_set": ["+", "-", "<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 123, "start": True, "end": False},
            {"id": 124, "start": False, "end": True},
            {"id": 125, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 123,
                "state_dst_id": 125,
                "type": 1,
                "name": "Factor_prime",
                "predict": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 125,
                "state_dst_id": 124,
                "type": 1,
                "name": "G",
                "predict": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
            },
        ],
    },
    {
        "name": "Term_zegond",
        "predict_set": {"NUM", "("},
        "follow_set": ["+", "-", "<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 126, "start": True, "end": False},
            {"id": 127, "start": False, "end": True},
            {"id": 128, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 126,
                "state_dst_id": 128,
                "type": 1,
                "name": "Factor_zegond",
                "predict": {"NUM", "("},
            },
            {
                "state_src_id": 128,
                "state_dst_id": 127,
                "type": 1,
                "name": "G",
                "predict": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
            },
        ],
    },
    {
        "name": "G",
        "predict_set": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
        "follow_set": ["+", "-", "<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 129, "start": True, "end": False},
            {"id": 130, "start": False, "end": True},
            {"id": 131, "start": False, "end": False},
            {"id": 132, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 129,
                "state_dst_id": 131,
                "type": 0,
                "name": "*",
                "predict": ["*"],
            },
            {
                "state_src_id": 131,
                "state_dst_id": 132,
                "type": 1,
                "name": "Factor",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 132,
                "state_dst_id": 130,
                "type": 1,
                "name": "G",
                "predict": {";", "+", ")", "]", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 129,
                "state_dst_id": 130,
                "type": 2,
                "name": "ε",
                "predict": ["+", "-", "<", "==", ";", ")", "]", ","],
            },
        ],
    },
    {
        "name": "Factor",
        "predict_set": {"ID", "NUM", "("},
        "follow_set": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "states": [
            {"id": 133, "start": True, "end": False},
            {"id": 134, "start": False, "end": True},
            {"id": 135, "start": False, "end": False},
            {"id": 136, "start": False, "end": False},
            {"id": 137, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 133,
                "state_dst_id": 135,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 135,
                "state_dst_id": 136,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 136,
                "state_dst_id": 134,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 133,
                "state_dst_id": 137,
                "type": 0,
                "name": "ID",
                "predict": ["ID"],
            },
            {
                "state_src_id": 137,
                "state_dst_id": 134,
                "type": 1,
                "name": "Var_call_prime",
                "predict": {";", "+", ")", "(", "]", "[", ",", "==", "*", "-", "<"},
            },
            {
                "state_src_id": 133,
                "state_dst_id": 134,
                "type": 0,
                "name": "NUM",
                "predict": ["NUM"],
            },
        ],
    },
    {
        "name": "Var_call_prime",
        "predict_set": {";", "+", ")", "(", "]", "[", ",", "==", "*", "-", "<"},
        "follow_set": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "states": [
            {"id": 138, "start": True, "end": False},
            {"id": 139, "start": False, "end": True},
            {"id": 140, "start": False, "end": False},
            {"id": 141, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 138,
                "state_dst_id": 140,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 140,
                "state_dst_id": 141,
                "type": 1,
                "name": "Args",
                "predict": {"ID", ")", "NUM", "("},
            },
            {
                "state_src_id": 141,
                "state_dst_id": 139,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 138,
                "state_dst_id": 139,
                "type": 1,
                "name": "Var_prime",
                "predict": {";", "+", ")", "]", "[", ",", "==", "*", "-", "<"},
            },
        ],
    },
    {
        "name": "Var_prime",
        "predict_set": {";", "+", ")", "]", "[", ",", "==", "*", "-", "<"},
        "follow_set": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
        "states": [
            {"id": 142, "start": True, "end": False},
            {"id": 143, "start": False, "end": True},
            {"id": 144, "start": False, "end": False},
            {"id": 145, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 142,
                "state_dst_id": 144,
                "type": 0,
                "name": "[",
                "predict": ["["],
            },
            {
                "state_src_id": 144,
                "state_dst_id": 145,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 145,
                "state_dst_id": 143,
                "type": 0,
                "name": "]",
                "predict": ["]"],
            },
            {
                "state_src_id": 142,
                "state_dst_id": 143,
                "type": 2,
                "name": "ε",
                "predict": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
            },
        ],
    },
    {
        "name": "Factor_prime",
        "predict_set": {";", "+", ")", "(", "]", ",", "==", "*", "-", "<"},
        "follow_set": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 146, "start": True, "end": False},
            {"id": 147, "start": False, "end": True},
            {"id": 148, "start": False, "end": False},
            {"id": 149, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 146,
                "state_dst_id": 148,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 148,
                "state_dst_id": 149,
                "type": 1,
                "name": "Args",
                "predict": {"ID", ")", "NUM", "("},
            },
            {
                "state_src_id": 149,
                "state_dst_id": 147,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 146,
                "state_dst_id": 147,
                "type": 2,
                "name": "ε",
                "predict": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
            },
        ],
    },
    {
        "name": "Factor_zegond",
        "predict_set": {"NUM", "("},
        "follow_set": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
        "states": [
            {"id": 150, "start": True, "end": False},
            {"id": 151, "start": False, "end": True},
            {"id": 152, "start": False, "end": False},
            {"id": 153, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 150,
                "state_dst_id": 152,
                "type": 0,
                "name": "(",
                "predict": ["("],
            },
            {
                "state_src_id": 152,
                "state_dst_id": 153,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 153,
                "state_dst_id": 151,
                "type": 0,
                "name": ")",
                "predict": [")"],
            },
            {
                "state_src_id": 150,
                "state_dst_id": 151,
                "type": 0,
                "name": "NUM",
                "predict": ["NUM"],
            },
        ],
    },
    {
        "name": "Args",
        "predict_set": {"ID", ")", "NUM", "("},
        "follow_set": [")"],
        "states": [
            {"id": 154, "start": True, "end": False},
            {"id": 155, "start": False, "end": True},
        ],
        "transitions": [
            {
                "state_src_id": 154,
                "state_dst_id": 155,
                "type": 1,
                "name": "Arg_list",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 154,
                "state_dst_id": 155,
                "type": 2,
                "name": "ε",
                "predict": [")"],
            },
        ],
    },
    {
        "name": "Arg_list",
        "predict_set": {"ID", "NUM", "("},
        "follow_set": [")"],
        "states": [
            {"id": 156, "start": True, "end": False},
            {"id": 157, "start": False, "end": True},
            {"id": 158, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 156,
                "state_dst_id": 158,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 158,
                "state_dst_id": 157,
                "type": 1,
                "name": "Arg_list_prime",
                "predict": {")", ","},
            },
        ],
    },
    {
        "name": "Arg_list_prime",
        "predict_set": {")", ","},
        "follow_set": [")"],
        "states": [
            {"id": 159, "start": True, "end": False},
            {"id": 160, "start": False, "end": True},
            {"id": 161, "start": False, "end": False},
            {"id": 162, "start": False, "end": False},
        ],
        "transitions": [
            {
                "state_src_id": 159,
                "state_dst_id": 161,
                "type": 0,
                "name": ",",
                "predict": [","],
            },
            {
                "state_src_id": 161,
                "state_dst_id": 162,
                "type": 1,
                "name": "Expression",
                "predict": {"ID", "NUM", "("},
            },
            {
                "state_src_id": 162,
                "state_dst_id": 160,
                "type": 1,
                "name": "Arg_list_prime",
                "predict": {")", ","},
            },
            {
                "state_src_id": 159,
                "state_dst_id": 160,
                "type": 2,
                "name": "ε",
                "predict": [")"],
            },
        ],
    },
]


FOLLOW_SET = {
    "Program": ["\u0000"],
    "Declaration_list": [
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
    ],
    "Declaration": [
        "int",
        "void",
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
    ],
    "Declaration_initial": ["(", ";", "[", ",", ")"],
    "Declaration_prime": [
        "int",
        "void",
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
    ],
    "Var_declaration_prime": [
        "int",
        "void",
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
    ],
    "Fun_declaration_prime": [
        "int",
        "void",
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
    ],
    "Type_specifier": ["ID"],
    "Params": [")"],
    "Param_list": [")"],
    "Param": [",", ")"],
    "Param_prime": [",", ")"],
    "Compound_stmt": [
        "int",
        "void",
        "\u0000",
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Statement_list": ["}"],
    "Statement": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Expression_stmt": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Selection_stmt": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Else_stmt": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Iteration_stmt": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Return_stmt": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Return_stmt_prime": [
        "{",
        "break",
        ";",
        "if",
        "repeat",
        "return",
        "ID",
        "(",
        "NUM",
        "}",
        "endif",
        "else",
        "until",
    ],
    "Expression": [";", ")", "]", ","],
    "B": [";", ")", "]", ","],
    "H": [";", ")", "]", ","],
    "Simple_expression_zegond": [";", ")", "]", ","],
    "Simple_expression_prime": [";", ")", "]", ","],
    "C": [";", ")", "]", ","],
    "Relop": ["(", "ID", "NUM"],
    "Additive_expression": [";", ")", "]", ","],
    "Additive_expression_prime": ["<", "==", ";", ")", "]", ","],
    "Additive_expression_zegond": ["<", "==", ";", ")", "]", ","],
    "D": ["<", "==", ";", ")", "]", ","],
    "Addop": ["(", "ID", "NUM"],
    "Term": ["+", "-", ";", ")", "<", "==", "]", ","],
    "Term_prime": ["+", "-", "<", "==", ";", ")", "]", ","],
    "Term_zegond": ["+", "-", "<", "==", ";", ")", "]", ","],
    "G": ["+", "-", "<", "==", ";", ")", "]", ","],
    "Factor": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
    "Var_call_prime": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
    "Var_prime": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
    "Factor_prime": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
    "Factor_zegond": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
    "Args": [")"],
    "Arg_list": [")"],
    "Arg_list_prime": [")"],
}
PREDICT_SET = {
    "1": ["int", "void", "\u0000"],
    "2": ["int", "void"],
    "3": ["\u0000", "{", "break", ";", "if", "repeat", "return", "ID", "(", "NUM", "}"],
    "4": ["int", "void"],
    "5": ["int", "void"],
    "6": ["("],
    "7": [";", "["],
    "8": [";"],
    "9": ["["],
    "10": ["("],
    "11": ["int"],
    "12": ["void"],
    "13": ["int"],
    "14": ["void"],
    "15": [","],
    "16": [")"],
    "17": ["int", "void"],
    "18": ["["],
    "19": [",", ")"],
    "20": ["{"],
    "21": ["{", "break", ";", "if", "repeat", "return", "ID", "(", "NUM"],
    "22": ["}"],
    "23": ["break", ";", "ID", "(", "NUM"],
    "24": ["{"],
    "25": ["if"],
    "26": ["repeat"],
    "27": ["return"],
    "28": ["ID", "(", "NUM"],
    "29": ["break"],
    "30": [";"],
    "31": ["if"],
    "32": ["endif"],
    "33": ["else"],
    "34": ["repeat"],
    "35": ["return"],
    "36": [";"],
    "37": ["ID", "(", "NUM"],
    "38": ["(", "NUM"],
    "39": ["ID"],
    "40": ["="],
    "41": ["["],
    "42": ["(", "*", "+", "-", "<", "==", ";", ")", "]", ","],
    "43": ["="],
    "44": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
    "45": ["(", "NUM"],
    "46": ["(", "*", "+", "-", "<", "==", ";", ")", "]", ","],
    "47": ["<", "=="],
    "48": [";", ")", "]", ","],
    "49": ["<"],
    "50": ["=="],
    "51": ["(", "ID", "NUM"],
    "52": ["(", "*", "+", "-", "<", "==", ";", ")", "]", ","],
    "53": ["(", "NUM"],
    "54": ["+", "-"],
    "55": ["<", "==", ";", ")", "]", ","],
    "56": ["+"],
    "57": ["-"],
    "58": ["(", "ID", "NUM"],
    "59": ["(", "*", "+", "-", "<", "==", ";", ")", "]", ","],
    "60": ["(", "NUM"],
    "61": ["*"],
    "62": ["+", "-", "<", "==", ";", ")", "]", ","],
    "63": ["("],
    "64": ["ID"],
    "65": ["NUM"],
    "66": ["("],
    "67": ["[", "*", "+", "-", ";", ")", "<", "==", "]", ","],
    "68": ["["],
    "69": ["*", "+", "-", ";", ")", "<", "==", "]", ","],
    "70": ["("],
    "71": ["*", "+", "-", "<", "==", ";", ")", "]", ","],
    "72": ["("],
    "73": ["NUM"],
    "74": ["ID", "(", "NUM"],
    "75": [")"],
    "76": ["ID", "(", "NUM"],
    "77": [","],
    "78": [")"],
}


def get_non_terminal_predict_set(non_terminal, production_rules_dict):
    production_rules = production_rules_dict[non_terminal][1]
    return reduce(
        lambda x, y: x.union(set(y)),
        [PREDICT_SET[str(pr_no)] for pr_no, _ in production_rules],
        set(),
    )


def get_transition_diagram():
    transition_diagram = []
    state_no = 1
    production_rules_dict = get_production_rules()
    for rule_name, production_rules in production_rules_dict.values():
        diagram = {
            "name": rule_name,
            "predict_set": get_non_terminal_predict_set(
                rule_name, production_rules_dict
            ),
            "follow_set": FOLLOW_SET[rule_name],
        }
        start_state = state_no
        final_state = state_no + 1
        state_no += 2
        states = [
            {"id": start_state, "start": True, "end": False},
            {"id": final_state, "start": False, "end": True},
        ]
        transitions = []
        for pr_no, pr in production_rules:
            previous_state = start_state
            for transition_no, transition in enumerate(pr):
                is_final = transition_no == len(pr) - 1
                if not is_final:
                    states.append({"id": state_no, "start": False, "end": False})
                transitions.append(
                    {
                        "state_src_id": previous_state,
                        "state_dst_id": final_state if is_final else state_no,
                        "type": SymbolType.NON_TERMINAL.value
                        if transition in FOLLOW_SET
                        else SymbolType.EPSILON.value
                        if transition == "ε"
                        else SymbolType.TERMINAL.value,
                        "name": transition,
                        "predict": get_non_terminal_predict_set(
                            transition, production_rules_dict
                        )
                        if transition in FOLLOW_SET
                        else PREDICT_SET.get(str(pr_no), {})
                        if transition == "ε"
                        else [transition],
                    }
                )
                previous_state = state_no
                state_no += 0 if is_final else 1
        diagram["states"] = states
        diagram["transitions"] = transitions
        transition_diagram.append(diagram)
    return re.sub("\\\\x00", "$", re.sub("┤", "$", str(transition_diagram)))
